#! /usr/bin/php
<?php 

require __DIR__ . '/vendor/autoload.php';

use SamsungTV\Remote;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

$oLogger = new Logger("remote");
$oLogger->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));

$sKey = $_SERVER['argv'][1];

$oRemote = new Remote($oLogger);
$oRemote->setHost("192.168.10.36")->sendKey($sKey);

